### ISSUE TITLE
Create new citrus carousel image

### ISSUE THREAD

**Issue by suryasaha** [solgenomics/citrusgreening#23]

**Comment by phosmani** [comment]
This will be IRCHLB meeting banner carousel. Get the background image from the organizers (Tim Gottwald and Clark Baxley). Update information for next meeting and add links.

**Comment by suryasaha** [comment]
Thats a separate issue :-)

This is to replace the citrus image that was taken from some web page. We should not be using it. Try finding a copyright free stock image. Maybe from https://pixabay.com/en/photos/?q=citrus&image_type=&cat=&order=
